## This theme generated automatically by themer
## script local to this machine
foreground                      #b8b5b1
background                      #1c1b1a
selection_foreground            #4a4733
selection_background            #e3cba5
# Cursor colors
cursor                          #d4af37
cursor_text_color               #1c1b1a
# URL underline color when hovering with mouse
# kitty window border colors
# OS Window titlebar colors
# Tab bar colors
active_tab_foreground           #e3cba5
active_tab_background           #4a4733
inactive_tab_foreground         #7a7875
inactive_tab_background         #262423
# Colors for marks (marked text in the terminal)
# The basic 16 colors
# black
color0 #151413
color8 #999690
# red
color1 #8c504a
color9 #c9776f
# green
color2  #76856a
color10 #96af88
# yellow
color3  #c2b280
color11 #e3cba5
# blue
color4  #6ab0c7
color12 #6ab0c7
# magenta
color5  #846b97
color13 #a48cb3
# cyan
color6  #c4824d
color14 #e3a274
# white
color7  #b8b5b1
color15 #e3cba5
# You can set the remaining 240 colors as color16 to color255.